---
title: "Assessment of Enzyme Resources and Diversity in the Fermented Food Microbiome"
author: "P.L. and J.S."
format: html
editor: visual
---

## Figure 2

```{r}
rm(list=ls())
library(data.table)
library(ggplot2)
library(viridis)
library(lessR)
library(tidyr)
library(dplyr)
```

```{r}
source_data_2_1 <- fread("./source_data_2.csv")
source_data_2_1|>count(how_know)

EC_table <- source_data_2_1 %>% 
  group_by(CLEAN_EC) %>% 
  summarise(
    all_ref = n_distinct(cluster_id),
    know = sum(labels == "known"),
    noval = sum(labels == "unknown")
  )

EC_table$EC1 <- EC_table$CLEAN_EC

EC_table <- EC_table %>%
  separate(EC1, into = c("EC1_1", "EC1_2", "EC1_3", "EC1_4"), sep = "\\.")
EC_table$new_clu_pro <- EC_table$noval/EC_table$all_ref *100
EC_pie <- EC_table %>%
  group_by(EC1_1) %>%
  summarise(
    count = n_distinct(CLEAN_EC),
    know = n_distinct(CLEAN_EC[new_clu_pro == 0]),
    noval = n_distinct(CLEAN_EC[new_clu_pro == 100]),
    others = n_distinct(CLEAN_EC[new_clu_pro != 0 & new_clu_pro != 100])
  )
EC_pie$EC1_1 <- c("EC_1","EC_2","EC_3","EC_4","EC_5","EC_6","EC_7")
EC_pie_long <- EC_pie %>%
  pivot_longer(
    cols = c(know,others,noval),
    names_to = "variable", 
    values_to = "value"
  )
```

```{r}
source_data_2_1$'EC_A' <- lapply(source_data_2_1$CLEAN_EC,function(x){
  return(stringr::str_split(x,"\\.")[1][[1]][1])
})|>unlist()

source_data_2_1$'EC_B' <- lapply(source_data_2_1$CLEAN_EC,function(x){
  return(stringr::str_split(x,"\\.")[1][[1]][2])
})|>unlist()


source_data_2_1$'EC_A' <- paste0("EC: ",source_data_2_1$'EC_A')
source_data_2_1$EC_B <- paste0(source_data_2_1$'EC_A',".",source_data_2_1$'EC_B',"._._")

source_data_2_1 <- source_data_2_1[,"EC_cluster_sum":=length(unique(cluster_id)),by = "EC_B"]

source_data_2_1$'known' <- ifelse(source_data_2_1$how_know,1,0)
source_data_2_1 <- source_data_2_1[,"known_sum" := sum(known),by = "EC_B" ]
source_data_2_1$'unknown_sum' <- source_data_2_1$EC_cluster_sum-source_data_2_1$'known_sum'
source_data_2_1$unknown_per <- 1-(source_data_2_1$known_sum /source_data_2_1$EC_cluster_sum)
source_data_2_1$EC_B <- paste0(source_data_2_1$EC_B,"(",(source_data_2_1$unknown_per*100)|>round(2) ,"%)")


source_data_2_1 <- source_data_2_1[,"EC_A_known_sum" := sum(known),by = "EC_A" ]
source_data_2_1 <- source_data_2_1[,"EC_A_cluster_sum":=length(unique(cluster_id)),by = "EC_A"]
source_data_2_1$"EC_A_unknown_per" <-  1-(source_data_2_1$EC_A_known_sum /source_data_2_1$EC_A_cluster_sum)
source_data_2_1$"EC_A" <-  paste0(source_data_2_1$EC_A,"\n(",(source_data_2_1$EC_A_unknown_per*100)|>round(2) ,"%)")

colnames(source_data_2_1)
```

```{r}
source_data_2_1_ex <- source_data_2_1[,c(7,9,14,17)]|>unique()
source_data_2_1_ex$EC_B <- source_data_2_1_ex$EC_B|>stringr::str_extract(".*(?=\\()")
source_data_2_1_ex <- source_data_2_1_ex|> arrange(EC_A, desc(unknown_per))
source_data_2_1_ex$EC_B <- factor(source_data_2_1_ex$EC_B,levels=rev(unique(source_data_2_1_ex$EC_B)))
colnames(source_data_2_1_ex)
```

```{r}
source_data_2_3 <- source_data_2_1[,c(1,2,4:8)]
source_data_2_3$how_know <- ifelse(source_data_2_3$how_know,"known","unknown")
```

```{r}
figure_2_a <- PieChart(labels ,data= source_data_2_1,
         hole = 0.4,
         labels_size=1,
         color = "black",
         fill = c( "#F4FAFE", "#4981BF"),
         labels_color = c("#4981BF","#F4FAFE"),
         main = NULL)
figure_2_a
```

```{r}
library(ggsignif)
library(ggpubr)
library(patchwork)

figure_2_b <- ggplot(source_data_2_3,aes(x = how_know, y = cluster_members, fill = how_know))+
  geom_violin(aes(fill = how_know),) +
  geom_boxplot(fill = "white",width = 0.1,color="black")+
  # stat_compare_means(method = "wilcox.test",label.x.npc = "middle",label.y.npc = "top",label = "p.signif")+
  stat_compare_means(method = "wilcox.test",label.y = 3.5,label.x.npc = "left")+
  # stat_compare_means(method = "wilcox.test",label.y.npc = "top")+
  scale_fill_manual(values = c("#F4FAFE","#4981BF"))+
  scale_y_log10()+
  # coord_flip()+
  xlab('') +
  theme_classic()+
  theme(legend.position = "none")
```

```{r}
figure_2_c <- ggplot(source_data_2_1_ex, aes(x = unknown_per, y = EC_B, fill = EC_A)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = paste0(round(unknown_per, 4) * 100, "%")),
            position = position_dodge(0.85),
            hjust = -0.2, size = 2) +
  scale_x_continuous(limits = c(0, 1.05)) +   
  scale_fill_manual(values = ggsci::pal_simpsons("springfield")(7)) +
  coord_flip() +
  labs(x = "unknown rate", y = "EC_level2", fill = "EC_level1 (unknown rate)") +
  theme_classic() +
  theme()
```
