---
title: "Assessment of Enzyme Resources and Diversity in the Fermented Food Microbiome"
author: "P.L. and J.S."
format: html
editor: visual
---

## Figure 1

```{r}
rm(list=ls())
require(data.table)
require(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
table0 <- fread("./select_fin.csv")
table0 <- table0[table0$confidence>=0.2 & table0$cluster_members > table0$uniprot_members_total,]
table1 <- table0|>count(CLEAN_EC)
table1$'EC_A' <- lapply(table1$CLEAN_EC,function(x){
  return(stringr::str_split(x,"\\.")[1][[1]][1])
})|>unlist()
table1 <- table1[,"EC_A_count":=sum(n),by =c("EC_A")]
table1 <- table1[,"EC_A_mem":=length(unique(CLEAN_EC)),by =c("EC_A")]
table2 <- unique(table1[,c(3:5)])
table2$'per' <- table2$EC_A_count/98693
table2$EC_A <- paste0("EC ",table2$EC_A)
colnames(table2) <- c("EC_id","within enzyme_clusters","unique_EC_numbers","percent_of_enzyme_clusters ")
table2$'average_EC_clusters' <- table2$`within enzyme_clusters`/table2$unique_EC_numbers
table2$'id' <- paste(table2$EC_id,"\n","( n=",table2$`within enzyme_clusters`,")")
```

```{r}
table3 <- table2[,c(1,3,5)]
table3 <- melt(table3,id.vars= c("EC_id"))
table3$value <- table3$value|>round(2)
```

```{r}
source_data_1_1 <- fread("./source_data_1_1.csv")

test <- fread("./clean_0.2.fasta")
test$`>AlvarezOrdonezA_xxxx__C02-19__bin.10XXXXXC02-19_k141_10463.p1`[grepl(">",test$`>AlvarezOrdonezA_xxxx__C02-19__bin.10XXXXXC02-19_k141_10463.p1`)]|>unique()|>length()

kegg_anno <- fread("./clean_kegg_anno_2024_09.csv")
# kegg_anno$cluster_id[kegg_anno$cluster_id %in% source_data_1_1$cluster_id]|>unique()|>length()
# source_data_1_1$cluster_id[source_data_1_1$cluster_id %in% kegg_anno$cluster_id]|>unique()|>length()

kegg_pathway <- fread("./kegg_pathway_2024_09.csv")
kegg_anno <- kegg_pathway[,c(3:7)][kegg_anno,on =c("kegg_ko"),allow.cartesian=TRUE]

# colnames(kegg_pathway)[8] <- "kegg_ko"
# kegg_anno <- kegg_pathway[,c(3,5,7,8)][kegg_anno,on =c("kegg_ko"),allow.cartesian=TRUE]

kegg_anno <- kegg_anno[cluster_id %in% source_data_1_1$cluster_id,]
kegg_anno$kegg_EC <- c()

kegg_anno_bind1 <- kegg_anno[,c(1,4,5)][source_data_1_1, on =c("cluster_id"),]|>unique()
kegg_anno_bind2 <- kegg_anno[,c(1,2,4,5)][source_data_1_1, on =c("cluster_id"),]|>unique()
# kegg_anno_bind3 <- kegg_anno[,c(3,4,5)][source_data_1_1, on =c("cluster_id"),]|>unique()

source_data_1_1.5_1 <- kegg_anno_bind1[,c(1,3,13)]|>unique()
source_data_1_1.5_1 <- source_data_1_1.5_1[,"total_type":=length(unique(cluster_id)),by = c("how_know")]
source_data_1_1.5_1 <- source_data_1_1.5_1[,"pathway_type":=length(unique(cluster_id)),by = c("how_know","level1_pathway_name")]
source_data_1_1.5_1$'pathway_percent' <- source_data_1_1.5_1$pathway_type/source_data_1_1.5_1$total_type
source_data_1_1.5_1 <- unique(source_data_1_1.5_1[,c(1,3,6)])

source_data_1_1.5_2 <- kegg_anno_bind2[,c(1,2,4,14)]|>unique()
source_data_1_1.5_2 <- source_data_1_1.5_2[,"total_type":=length(unique(cluster_id)),by = c("how_know")]
source_data_1_1.5_2 <- source_data_1_1.5_2[,"pathway_type":=length(unique(cluster_id)),by = c("how_know","level2_pathway_name")]
source_data_1_1.5_2$'pathway_percent' <- source_data_1_1.5_2$pathway_type/source_data_1_1.5_2$total_type

source_data_1_1.5_2 <- unique(source_data_1_1.5_2[,c(1,2,4,7)])
```

```{r}
table4 <- kegg_anno_bind1[,"pathway_type":=length(unique(cluster_id)),by = c("level1_pathway_name")]
# table4$pathway_percent <- table4$pathway_type/length(unique(table4$cluster_id))
# table4 <- unique(table4[,c(1,14,15)])
kegg_anno_bind2 <- kegg_anno_bind2[kegg_anno_bind2$level1_pathway_name == "09100 Metabolism",]
table5 <- kegg_anno_bind2[,"pathway_type":=length(unique(cluster_id)),by = c("level2_pathway_name")]
table5$pathway_percent <- table5$pathway_type/length(unique(kegg_anno_bind1$cluster_id))
table5 <- unique(table5[,c(2,15,16)])
```

```{r}
table6 <- fread("./Euk_Bac_EC.csv")
library(ggVennDiagram)

x <- list("Eukaryota" = table6$CLEAN_EC[table6$superkingdom == "Eukaryota"],
          "Bacteria" = table6$CLEAN_EC[table6$superkingdom != "Eukaryota"])


figure_1_b <- ggVennDiagram(x, lwd = 0.7) + 
  scale_fill_gradient(low = "#708FBA", high = "#D06D60") +
  xlim(-10, 10) +
  theme(legend.position = "none",
        plot.margin = grid::unit(c(10, 0, 10, 0), "pt")
  )
```

```{r}
library(treemapify)
library(ggplot2)

figure_1_c <- ggplot(table2, aes(area = `within enzyme_clusters`, fill = `within enzyme_clusters`, label = id)) +
  geom_treemap() +
  geom_treemap_text(colour = "white",
                    place = "centre",
                    size = 15) 
figure_1_c
```

```{r}
figure_1_d_1 <- ggplot(table3[table3$variable == "average_EC_clusters",], aes(
  x = EC_id, 
  y = value,
  fill = variable)) +
  geom_bar(stat = 'identity') +
  geom_text(aes(label = value, fill = NULL),
            vjust = -1.2, size = 4, color = "black") +
  scale_fill_manual(values = c("#708FBA")) +
  scale_y_continuous(limits = c(0, 60)) +
  labs(y = "average clusters of each EC") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        panel.grid = element_blank(),
        strip.background.x = element_rect(
          color = "white", fill = "white", size = 1.5, linetype = "solid"),
        strip.placement = "outside",
        axis.text.y = element_blank(),
        axis.text.x = element_text(hjust = .55),
        axis.ticks.y = element_blank(),
        legend.title = element_blank(),
        legend.position = "none",
        plot.margin = grid::unit(c(0, 0, 0, 0), "pt")  # Use grid::unit() here
  )

figure_1_d_2 <- ggplot(table3[table3$variable != "average_EC_clusters",], aes(
  x = EC_id, 
  y = value,
  fill = variable)) +
  geom_bar(stat = 'identity') +
  geom_text(aes(label = value, fill = NULL),
            vjust = 1.2, size = 4, color = "black") +
  scale_fill_manual(values = c("#D06D60")) +
  scale_x_discrete(position = "top") +
  scale_y_reverse(limits = c(950, 0)) +
  labs(y = "unique clusters of whole EC") +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        panel.grid = element_blank(),
        strip.background.x = element_rect(
          color = "white", fill = "white", size = 1.5, linetype = "solid"),
        strip.placement = "outside",
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        legend.title = element_blank(),
        legend.position = "none",
        plot.margin = grid::unit(c(0, 0, 0, 0), "pt")  # Use grid::unit() for margins
  )

require(patchwork)
figure_1_d <- figure_1_d_1/figure_1_d_2
figure_1_d
```

```{r}
library(lessR)
table4_ex <- table4[,c(1,3,4)]
table4_ex$level1_pathway_name[is.na(table4_ex$level1_pathway_name)] <- "No annotation"
table4_ex$level1_pathway_name2 <- table4_ex$level1_pathway_name
table4_ex <- table4_ex %>%
  separate(level1_pathway_name2, into = c("level1", "step1"), sep = " ")

figure_1_e <- PieChart(level1_pathway_name, data = table4_ex,main = NULL,
                   labels = "input")
figure_1_e
```

```{r}
figure_1_f <- ggplot(table5,aes(x = reorder(level2_pathway_name,pathway_type), y = pathway_type))+
  geom_bar(stat='identity',position = 'dodge',fill = "#708FBA",width = 0.6)+
  geom_text(aes(label = pathway_type,fill = NULL),
            hjust = 1.2,size= 4,color = "black")+
  scale_y_continuous(limits = c(0,max(table5$pathway_type)*1.15),expand = c(0,0))+
  coord_flip()+
  labs(y= "clusters within pathway",x = "")+
  theme_classic()+
  theme(legend.position="none",
          plot.title = element_text(size=11),
          axis.text.x = element_text(angle = 30,vjust = 0.85,hjust = 0.75))

figure_1_f 
```
